// Co-authored by FORGE (Session: forge-20260327063704-3049883)
// src/apex/canvas/CanvasServer.ts — JAL-013 Canvas WebSocket + REST server
//
// Starts an HTTP server with WebSocket upgrade support.
// Binds to 127.0.0.1 only — never exposed to the network unless explicitly configured.
//
// WebSocket:
//   - Auth via session token as query param: ws://localhost:7474/ws?token=<token>
//   - On connect: immediately sends a full system.status snapshot as the first message.
//   - Subscribes to EventBus and fans out all events to connected clients.
//
// REST:
//   GET  /status                          — current environment snapshot
//   GET  /tasks                           — recent task history (up to 20)
//   GET  /memory/episodic                 — recent episodic entries
//   GET  /memory/durable                  — durable context
//   GET  /policy/allowlist                — package allowlist
//   POST /approvals/:id/approve           — approve a pending Tier 2 token (auth required)
//   POST /approvals/:id/deny              — deny a pending Tier 2 token (auth required)
//
// SAFETY GATE: approval endpoints require Authorization: Bearer <sessionToken>.
// SAFETY GATE: server binds to 127.0.0.1 only (host override must be explicit).

import * as http from 'http';
import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { URL } from 'url';
import { WebSocketServer, WebSocket } from 'ws';
import { EventBus } from './EventBus';
import { CanvasEvent, EnvironmentSnapshot } from '../types';
import { ApprovalService } from '../policy/ApprovalService';
import { CheckpointStore } from '../checkpoint/CheckpointStore';
import { EpisodicStore } from '../memory/EpisodicStore';
import { DurableStore } from '../memory/DurableStore';
import { PackageAllowlist } from '../policy/PackageAllowlist';
import { IAuditLog } from '../policy/AuditLog';
import { handleStatus, sendJson } from './routes/statusRoutes';
import { handleTasks } from './routes/taskRoutes';
import { handleEpisodic, handleDurable } from './routes/memoryRoutes';
import { handleAllowlist } from './routes/policyRoutes';
import { handleApprove, handleDeny, isAuthorized } from './routes/approvalRoutes';
import { PluginCoordinator } from '../plugins/PluginCoordinator';

// ── Constants ─────────────────────────────────────────────────────────────────

const DEFAULT_PORT = 7474;
const DEFAULT_HOST = '127.0.0.1';

/**
 * Path to the Vite-built Canvas frontend dist directory.
 * Resolved relative to this file so it works regardless of cwd.
 */
const UI_DIST_DIR = path.resolve(__dirname, 'ui', 'dist');

/** MIME type map for static file serving */
const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.mjs':  'application/javascript; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.svg':  'image/svg+xml',
  '.png':  'image/png',
  '.ico':  'image/x-icon',
  '.json': 'application/json; charset=utf-8',
  '.map':  'application/json; charset=utf-8',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf':  'font/ttf',
};

// ── CanvasServerDeps ──────────────────────────────────────────────────────────

/** Services injected into CanvasServer at construction time. */
export interface CanvasServerDeps {
  /**
   * Session token generated by ApexRuntime at startup.
   * May be empty string at construction time — must be set via setSessionToken()
   * before start() is called.
   */
  sessionToken: string;
  /** Event bus shared with ApexRuntime for publishing/subscribing to Canvas events. */
  eventBus: EventBus;
  approvalService: ApprovalService;
  checkpointStore: CheckpointStore;
  episodicStore: EpisodicStore;
  durableStore: DurableStore;
  allowlist: PackageAllowlist;
  auditLog: IAuditLog;
  /** Called to collect a fresh environment snapshot (used for initial WS snapshot + GET /status). */
  getSnapshot: () => EnvironmentSnapshot;
  /**
   * Plugin coordinator (JAL-016). Optional — if not provided, plugin routes return 404.
   */
  pluginCoordinator?: PluginCoordinator;
}

// ── CanvasServerOptions ───────────────────────────────────────────────────────

export interface CanvasServerOptions {
  /**
   * TCP port for the Canvas server.
   * Reads APEX_CANVAS_PORT env var; defaults to 7474.
   */
  port?: number;
  /**
   * Bind host.
   * SAFETY GATE: defaults to 127.0.0.1. Setting to 0.0.0.0 requires explicit opt-in.
   */
  host?: string;
}

// ── CanvasServer ──────────────────────────────────────────────────────────────

export class CanvasServer {
  private readonly port: number;
  private readonly host: string;
  // deps is mutable so ApexRuntime can inject the session token after construction
  private readonly deps: CanvasServerDeps;
  private httpServer: http.Server | null = null;
  private wss: WebSocketServer | null = null;
  private readonly clients = new Set<WebSocket>();

  constructor(deps: CanvasServerDeps, options: CanvasServerOptions = {}) {
    this.deps = deps;
    this.port = options.port ?? Number(process.env['APEX_CANVAS_PORT'] ?? DEFAULT_PORT);
    // SAFETY GATE: localhost only by default
    this.host = options.host ?? DEFAULT_HOST;
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  /**
   * Start the Canvas HTTP + WebSocket server.
   * Binds to this.host:this.port. Subscribes to EventBus.
   */
  start(): Promise<void> {
    return new Promise((resolve, reject) => {
      const server = http.createServer((req, res) => this.handleRequest(req, res));
      this.httpServer = server;

      // WebSocket server attached to the same HTTP server (upgrade event)
      const wss = new WebSocketServer({ noServer: true });
      this.wss = wss;

      // Authenticate WebSocket upgrade requests via session token query param
      server.on('upgrade', (req, socket, head) => {
        const baseUrl = `http://${req.headers.host ?? 'localhost'}`;
        let token: string | null = null;
        try {
          const parsed = new URL(req.url ?? '', baseUrl);
          if (parsed.pathname === '/ws') {
            token = parsed.searchParams.get('token');
          }
        } catch {
          // malformed URL — deny
        }

        if (token !== this.deps.sessionToken) {
          socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
          socket.destroy();
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'warn',
            service: 'CanvasServer',
            message: 'WebSocket upgrade rejected: invalid token',
            action: 'canvas.ws.auth_failed',
          });
          return;
        }

        wss.handleUpgrade(req, socket, head, (ws) => {
          wss.emit('connection', ws, req);
        });
      });

      // Client connected — send initial snapshot, register for events
      wss.on('connection', (ws: WebSocket) => {
        this.clients.add(ws);
        this.deps.auditLog.write({
          timestamp: new Date().toISOString(),
          level: 'info',
          service: 'CanvasServer',
          message: 'WebSocket client connected',
          action: 'canvas.ws.connected',
          client_count: this.clients.size,
        });

        // Send full system snapshot as the first message
        this.sendSnapshot(ws);

        ws.on('close', () => {
          this.clients.delete(ws);
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'info',
            service: 'CanvasServer',
            message: 'WebSocket client disconnected',
            action: 'canvas.ws.disconnected',
            client_count: this.clients.size,
          });
        });

        ws.on('error', (err) => {
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'warn',
            service: 'CanvasServer',
            message: `WebSocket client error: ${err.message}`,
            action: 'canvas.ws.error',
          });
          this.clients.delete(ws);
        });
      });

      // Subscribe to EventBus — fan out to all connected clients
      this.deps.eventBus.subscribe(this.broadcastEvent.bind(this));

      server.on('error', (err) => {
        reject(err);
      });

      server.listen(this.port, this.host, () => {
        this.deps.auditLog.write({
          timestamp: new Date().toISOString(),
          level: 'info',
          service: 'CanvasServer',
          message: `Canvas server listening on ${this.host}:${this.port}`,
          action: 'canvas.server.start',
          port: this.port,
          host: this.host,
        });
        resolve();
      });
    });
  }

  /**
   * Stop the Canvas server gracefully.
   * Closes all WebSocket connections, then closes the HTTP server.
   */
  stop(): Promise<void> {
    return new Promise((resolve) => {
      this.deps.eventBus.clear();

      // Close all WebSocket clients
      for (const ws of this.clients) {
        ws.terminate();
      }
      this.clients.clear();

      if (this.wss) {
        this.wss.close();
        this.wss = null;
      }

      if (this.httpServer) {
        this.httpServer.close(() => {
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'info',
            service: 'CanvasServer',
            message: 'Canvas server stopped',
            action: 'canvas.server.stop',
          });
          resolve();
        });
        this.httpServer = null;
      } else {
        resolve();
      }
    });
  }

  /** Broadcast a Canvas event to all connected WebSocket clients. */
  broadcastEvent(event: CanvasEvent): void {
    if (this.clients.size === 0) return;
    const data = JSON.stringify(event);
    for (const ws of this.clients) {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(data);
      }
    }
  }

  /**
   * Update the session token. Must be called before start() if the token
   * was not available at construction time (e.g. when ApexRuntime generates
   * it lazily in start()).
   */
  setSessionToken(token: string): void {
    this.deps.sessionToken = token;
  }

  get port_(): number {
    return this.port;
  }

  get connectedClients(): number {
    return this.clients.size;
  }

  // ── REST Request Handler ──────────────────────────────────────────────────

  private handleRequest(req: http.IncomingMessage, res: http.ServerResponse): void {
    const method = req.method ?? 'GET';
    const baseUrl = `http://${req.headers.host ?? 'localhost'}`;
    let pathname = '/';
    try {
      pathname = new URL(req.url ?? '/', baseUrl).pathname;
    } catch {
      sendJson(res, 400, { success: false, error: 'Bad request URI' });
      return;
    }

    // GET /canvas and GET /canvas/* — serve static frontend files
    if (method === 'GET' && (pathname === '/canvas' || pathname.startsWith('/canvas/'))) {
      this.serveStatic(req, res, pathname);
      return;
    }

    // GET /status
    if (method === 'GET' && pathname === '/status') {
      handleStatus(req, res, { getSnapshot: this.deps.getSnapshot });
      return;
    }

    // GET /tasks
    if (method === 'GET' && pathname === '/tasks') {
      handleTasks(req, res, { checkpointStore: this.deps.checkpointStore });
      return;
    }

    // GET /memory/episodic
    if (method === 'GET' && pathname === '/memory/episodic') {
      handleEpisodic(req, res, {
        episodicStore: this.deps.episodicStore,
        durableStore: this.deps.durableStore,
      });
      return;
    }

    // GET /memory/durable
    if (method === 'GET' && pathname === '/memory/durable') {
      handleDurable(req, res, {
        episodicStore: this.deps.episodicStore,
        durableStore: this.deps.durableStore,
      });
      return;
    }

    // GET /policy/allowlist
    if (method === 'GET' && pathname === '/policy/allowlist') {
      handleAllowlist(req, res, { allowlist: this.deps.allowlist });
      return;
    }

    // POST /approvals/:id/approve
    const approveMatch = /^\/approvals\/([^/]+)\/approve$/.exec(pathname);
    if (method === 'POST' && approveMatch) {
      const id = approveMatch[1]!;
      handleApprove(req, res, {
        approvalService: this.deps.approvalService,
        sessionToken: this.deps.sessionToken,
      }, id);
      return;
    }

    // POST /approvals/:id/deny
    const denyMatch = /^\/approvals\/([^/]+)\/deny$/.exec(pathname);
    if (method === 'POST' && denyMatch) {
      const id = denyMatch[1]!;
      handleDeny(req, res, {
        approvalService: this.deps.approvalService,
        sessionToken: this.deps.sessionToken,
      }, id);
      return;
    }

    // GET /apex/plugin-actions/:workspace_id (JAL-016)
    const pluginQueueMatch = /^\/apex\/plugin-actions\/([^/]+)$/.exec(pathname);
    if (method === 'GET' && pluginQueueMatch) {
      const workspaceId = decodeURIComponent(pluginQueueMatch[1]!);
      if (!this.deps.pluginCoordinator) {
        sendJson(res, 404, { success: false, error: 'Plugin coordinator not configured' });
        return;
      }
      const actions = this.deps.pluginCoordinator.dequeueActions(workspaceId);
      sendJson(res, 200, { success: true, actions });
      return;
    }

    // POST /apex/plugin-actions/:workspace_id/ack/:action_id (JAL-016)
    const pluginAckMatch = /^\/apex\/plugin-actions\/([^/]+)\/ack\/([^/]+)$/.exec(pathname);
    if (method === 'POST' && pluginAckMatch) {
      const workspaceId = decodeURIComponent(pluginAckMatch[1]!);
      const actionId = decodeURIComponent(pluginAckMatch[2]!);
      if (!this.deps.pluginCoordinator) {
        sendJson(res, 404, { success: false, error: 'Plugin coordinator not configured' });
        return;
      }
      // Read POST body
      const chunks: Buffer[] = [];
      req.on('data', (c: Buffer) => chunks.push(c));
      req.on('end', () => {
        try {
          const body = JSON.parse(Buffer.concat(chunks).toString('utf-8')) as Record<string, unknown>;
          const action = {
            action_id: actionId,
            workspace_id: workspaceId,
            action_type: body['action_type'] as 'approve' | 'deny',
            actor_platform_id: body['actor_platform_id'] as string,
            plugin_name: body['plugin_name'] as string,
            approval_id: body['approval_id'] as string,
            /** token = PluginApprovalToken.token_id (single-use approval gate) */
            token: body['token'] as string,
            /** signature = HMAC-SHA256 of all other fields (relay authorization) */
            signature: body['signature'] as string,
            received_at: new Date().toISOString(),
          };
          const result = this.deps.pluginCoordinator!.acknowledgeAction(workspaceId, action);
          sendJson(res, result.success ? 200 : 403, result);
        } catch {
          sendJson(res, 400, { success: false, error: 'Invalid request body' });
        }
      });
      return;
    }

    // 404
    sendJson(res, 404, { success: false, error: 'Not found' });
  }

  // ── Private ───────────────────────────────────────────────────────────────

  /**
   * Serve static files from the Canvas UI dist directory.
   * Route: GET /canvas and GET /canvas/*
   *
   * - /canvas and /canvas/ serve index.html with the session token injected.
   * - /canvas/assets/... serves Vite-emitted asset files directly.
   * - For all other sub-paths, falls back to index.html (SPA single-page behaviour).
   *
   * If dist/ does not exist (i.e. the frontend has not been built), returns 404
   * with a plain-text hint rather than crashing.
   *
   * SAFETY: path traversal is blocked by resolving against UI_DIST_DIR and
   * verifying the resolved path is still inside it.
   */
  private serveStatic(
    _req: http.IncomingMessage,
    res: http.ServerResponse,
    pathname: string,
  ): void {
    // Resolve dist directory — 404 if not built yet
    if (!fs.existsSync(UI_DIST_DIR)) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('Canvas UI not built. Run: cd src/apex/canvas/ui && npm install && npm run build');
      return;
    }

    // Strip the /canvas prefix to get the relative path within dist/
    const relative = pathname === '/canvas' || pathname === '/canvas/'
      ? 'index.html'
      : pathname.slice('/canvas/'.length) || 'index.html';

    // SAFETY GATE: resolve to absolute path and verify it stays inside UI_DIST_DIR
    const resolved = path.resolve(UI_DIST_DIR, relative);
    if (!resolved.startsWith(UI_DIST_DIR + path.sep) && resolved !== UI_DIST_DIR) {
      res.writeHead(403, { 'Content-Type': 'text/plain' });
      res.end('Forbidden');
      return;
    }

    // If the file does not exist, fall back to index.html (SPA routing)
    let filePath = resolved;
    if (!fs.existsSync(filePath)) {
      filePath = path.join(UI_DIST_DIR, 'index.html');
    }

    const ext = path.extname(filePath).toLowerCase();
    const mimeType = MIME_TYPES[ext] ?? 'application/octet-stream';
    const isHtml = ext === '.html';

    try {
      let content = fs.readFileSync(filePath);

      if (isHtml) {
        // Inject session token as a global JS variable so the frontend can use it
        // for the WebSocket connection. SAFETY: token never stored in localStorage.
        const tokenScript = `<script>window.__APEX_TOKEN__ = ${JSON.stringify(this.deps.sessionToken)};</script>`;
        const html = content.toString('utf-8').replace(
          '<!-- __APEX_SESSION_TOKEN_SCRIPT__ -->',
          tokenScript,
        );
        content = Buffer.from(html, 'utf-8');
      }

      res.writeHead(200, {
        'Content-Type': mimeType,
        'Content-Length': content.length,
        // Security headers
        'X-Content-Type-Options': 'nosniff',
        'X-Frame-Options': 'SAMEORIGIN',
      });
      res.end(content);
    } catch (err) {
      this.deps.auditLog.write({
        timestamp: new Date().toISOString(),
        level: 'warn',
        service: 'CanvasServer',
        message: `Static file error: ${(err as Error).message}`,
        action: 'canvas.static.error',
      });
      res.writeHead(500, { 'Content-Type': 'text/plain' });
      res.end('Internal server error');
    }
  }

  /**
   * Build and send the initial system.status snapshot event to a newly
   * connected WebSocket client.
   */
  private sendSnapshot(ws: WebSocket): void {
    try {
      const snapshot = this.deps.getSnapshot();
      const event: CanvasEvent = {
        event_id: crypto.randomUUID(),
        event_type: 'system.status',
        task_id: null,
        tier: null,
        created_at: new Date().toISOString(),
        payload: snapshot as unknown as Record<string, unknown>,
      };
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify(event));
      }
    } catch (err) {
      this.deps.auditLog.write({
        timestamp: new Date().toISOString(),
        level: 'warn',
        service: 'CanvasServer',
        message: `Failed to send initial snapshot: ${(err as Error).message}`,
        action: 'canvas.ws.snapshot_error',
      });
    }
  }
}

// ── Canvas event factory helpers (used by ApexRuntime) ────────────────────────

/**
 * Build a CanvasEvent envelope with a fresh UUID and timestamp.
 * Caller provides event_type, task_id, tier, and payload.
 * Payload must never include credentials, tokens, or secrets.
 */
export function makeCanvasEvent(
  event_type: CanvasEvent['event_type'],
  payload: Record<string, unknown>,
  task_id: string | null = null,
  tier: CanvasEvent['tier'] = null,
): CanvasEvent {
  return {
    event_id: crypto.randomUUID(),
    event_type,
    task_id,
    tier,
    created_at: new Date().toISOString(),
    payload,
  };
}
