// Co-authored by FORGE (Session: forge-20260327063704-3049883)
// src/apex/canvas/CanvasServer.ts — JAL-013 Canvas WebSocket + REST server
//
// Starts an HTTP server with WebSocket upgrade support.
// Binds to 127.0.0.1 only — never exposed to the network unless explicitly configured.
//
// WebSocket:
//   - Auth via session token as query param: ws://localhost:7474/ws?token=<token>
//   - On connect: immediately sends a full system.status snapshot as the first message.
//   - Subscribes to EventBus and fans out all events to connected clients.
//
// REST:
//   GET  /status                          — current environment snapshot
//   GET  /tasks                           — recent task history (up to 20)
//   GET  /memory/episodic                 — recent episodic entries
//   GET  /memory/durable                  — durable context
//   GET  /policy/allowlist                — package allowlist
//   POST /approvals/:id/approve           — approve a pending Tier 2 token (auth required)
//   POST /approvals/:id/deny              — deny a pending Tier 2 token (auth required)
//
// SAFETY GATE: approval endpoints require Authorization: Bearer <sessionToken>.
// SAFETY GATE: server binds to 127.0.0.1 only (host override must be explicit).

import * as http from 'http';
import * as crypto from 'crypto';
import { URL } from 'url';
import { WebSocketServer, WebSocket } from 'ws';
import { EventBus } from './EventBus';
import { CanvasEvent, EnvironmentSnapshot } from '../types';
import { ApprovalService } from '../policy/ApprovalService';
import { CheckpointStore } from '../checkpoint/CheckpointStore';
import { EpisodicStore } from '../memory/EpisodicStore';
import { DurableStore } from '../memory/DurableStore';
import { PackageAllowlist } from '../policy/PackageAllowlist';
import { IAuditLog } from '../policy/AuditLog';
import { handleStatus, sendJson } from './routes/statusRoutes';
import { handleTasks } from './routes/taskRoutes';
import { handleEpisodic, handleDurable } from './routes/memoryRoutes';
import { handleAllowlist } from './routes/policyRoutes';
import { handleApprove, handleDeny, isAuthorized } from './routes/approvalRoutes';

// ── Constants ─────────────────────────────────────────────────────────────────

const DEFAULT_PORT = 7474;
const DEFAULT_HOST = '127.0.0.1';

// ── CanvasServerDeps ──────────────────────────────────────────────────────────

/** Services injected into CanvasServer at construction time. */
export interface CanvasServerDeps {
  /**
   * Session token generated by ApexRuntime at startup.
   * May be empty string at construction time — must be set via setSessionToken()
   * before start() is called.
   */
  sessionToken: string;
  /** Event bus shared with ApexRuntime for publishing/subscribing to Canvas events. */
  eventBus: EventBus;
  approvalService: ApprovalService;
  checkpointStore: CheckpointStore;
  episodicStore: EpisodicStore;
  durableStore: DurableStore;
  allowlist: PackageAllowlist;
  auditLog: IAuditLog;
  /** Called to collect a fresh environment snapshot (used for initial WS snapshot + GET /status). */
  getSnapshot: () => EnvironmentSnapshot;
}

// ── CanvasServerOptions ───────────────────────────────────────────────────────

export interface CanvasServerOptions {
  /**
   * TCP port for the Canvas server.
   * Reads APEX_CANVAS_PORT env var; defaults to 7474.
   */
  port?: number;
  /**
   * Bind host.
   * SAFETY GATE: defaults to 127.0.0.1. Setting to 0.0.0.0 requires explicit opt-in.
   */
  host?: string;
}

// ── CanvasServer ──────────────────────────────────────────────────────────────

export class CanvasServer {
  private readonly port: number;
  private readonly host: string;
  // deps is mutable so ApexRuntime can inject the session token after construction
  private readonly deps: CanvasServerDeps;
  private httpServer: http.Server | null = null;
  private wss: WebSocketServer | null = null;
  private readonly clients = new Set<WebSocket>();

  constructor(deps: CanvasServerDeps, options: CanvasServerOptions = {}) {
    this.deps = deps;
    this.port = options.port ?? Number(process.env['APEX_CANVAS_PORT'] ?? DEFAULT_PORT);
    // SAFETY GATE: localhost only by default
    this.host = options.host ?? DEFAULT_HOST;
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  /**
   * Start the Canvas HTTP + WebSocket server.
   * Binds to this.host:this.port. Subscribes to EventBus.
   */
  start(): Promise<void> {
    return new Promise((resolve, reject) => {
      const server = http.createServer((req, res) => this.handleRequest(req, res));
      this.httpServer = server;

      // WebSocket server attached to the same HTTP server (upgrade event)
      const wss = new WebSocketServer({ noServer: true });
      this.wss = wss;

      // Authenticate WebSocket upgrade requests via session token query param
      server.on('upgrade', (req, socket, head) => {
        const baseUrl = `http://${req.headers.host ?? 'localhost'}`;
        let token: string | null = null;
        try {
          const parsed = new URL(req.url ?? '', baseUrl);
          if (parsed.pathname === '/ws') {
            token = parsed.searchParams.get('token');
          }
        } catch {
          // malformed URL — deny
        }

        if (token !== this.deps.sessionToken) {
          socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
          socket.destroy();
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'warn',
            service: 'CanvasServer',
            message: 'WebSocket upgrade rejected: invalid token',
            action: 'canvas.ws.auth_failed',
          });
          return;
        }

        wss.handleUpgrade(req, socket, head, (ws) => {
          wss.emit('connection', ws, req);
        });
      });

      // Client connected — send initial snapshot, register for events
      wss.on('connection', (ws: WebSocket) => {
        this.clients.add(ws);
        this.deps.auditLog.write({
          timestamp: new Date().toISOString(),
          level: 'info',
          service: 'CanvasServer',
          message: 'WebSocket client connected',
          action: 'canvas.ws.connected',
          client_count: this.clients.size,
        });

        // Send full system snapshot as the first message
        this.sendSnapshot(ws);

        ws.on('close', () => {
          this.clients.delete(ws);
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'info',
            service: 'CanvasServer',
            message: 'WebSocket client disconnected',
            action: 'canvas.ws.disconnected',
            client_count: this.clients.size,
          });
        });

        ws.on('error', (err) => {
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'warn',
            service: 'CanvasServer',
            message: `WebSocket client error: ${err.message}`,
            action: 'canvas.ws.error',
          });
          this.clients.delete(ws);
        });
      });

      // Subscribe to EventBus — fan out to all connected clients
      this.deps.eventBus.subscribe(this.broadcastEvent.bind(this));

      server.on('error', (err) => {
        reject(err);
      });

      server.listen(this.port, this.host, () => {
        this.deps.auditLog.write({
          timestamp: new Date().toISOString(),
          level: 'info',
          service: 'CanvasServer',
          message: `Canvas server listening on ${this.host}:${this.port}`,
          action: 'canvas.server.start',
          port: this.port,
          host: this.host,
        });
        resolve();
      });
    });
  }

  /**
   * Stop the Canvas server gracefully.
   * Closes all WebSocket connections, then closes the HTTP server.
   */
  stop(): Promise<void> {
    return new Promise((resolve) => {
      this.deps.eventBus.clear();

      // Close all WebSocket clients
      for (const ws of this.clients) {
        ws.terminate();
      }
      this.clients.clear();

      if (this.wss) {
        this.wss.close();
        this.wss = null;
      }

      if (this.httpServer) {
        this.httpServer.close(() => {
          this.deps.auditLog.write({
            timestamp: new Date().toISOString(),
            level: 'info',
            service: 'CanvasServer',
            message: 'Canvas server stopped',
            action: 'canvas.server.stop',
          });
          resolve();
        });
        this.httpServer = null;
      } else {
        resolve();
      }
    });
  }

  /** Broadcast a Canvas event to all connected WebSocket clients. */
  broadcastEvent(event: CanvasEvent): void {
    if (this.clients.size === 0) return;
    const data = JSON.stringify(event);
    for (const ws of this.clients) {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(data);
      }
    }
  }

  /**
   * Update the session token. Must be called before start() if the token
   * was not available at construction time (e.g. when ApexRuntime generates
   * it lazily in start()).
   */
  setSessionToken(token: string): void {
    this.deps.sessionToken = token;
  }

  get port_(): number {
    return this.port;
  }

  get connectedClients(): number {
    return this.clients.size;
  }

  // ── REST Request Handler ──────────────────────────────────────────────────

  private handleRequest(req: http.IncomingMessage, res: http.ServerResponse): void {
    const method = req.method ?? 'GET';
    const baseUrl = `http://${req.headers.host ?? 'localhost'}`;
    let pathname = '/';
    try {
      pathname = new URL(req.url ?? '/', baseUrl).pathname;
    } catch {
      sendJson(res, 400, { success: false, error: 'Bad request URI' });
      return;
    }

    // GET /status
    if (method === 'GET' && pathname === '/status') {
      handleStatus(req, res, { getSnapshot: this.deps.getSnapshot });
      return;
    }

    // GET /tasks
    if (method === 'GET' && pathname === '/tasks') {
      handleTasks(req, res, { checkpointStore: this.deps.checkpointStore });
      return;
    }

    // GET /memory/episodic
    if (method === 'GET' && pathname === '/memory/episodic') {
      handleEpisodic(req, res, {
        episodicStore: this.deps.episodicStore,
        durableStore: this.deps.durableStore,
      });
      return;
    }

    // GET /memory/durable
    if (method === 'GET' && pathname === '/memory/durable') {
      handleDurable(req, res, {
        episodicStore: this.deps.episodicStore,
        durableStore: this.deps.durableStore,
      });
      return;
    }

    // GET /policy/allowlist
    if (method === 'GET' && pathname === '/policy/allowlist') {
      handleAllowlist(req, res, { allowlist: this.deps.allowlist });
      return;
    }

    // POST /approvals/:id/approve
    const approveMatch = /^\/approvals\/([^/]+)\/approve$/.exec(pathname);
    if (method === 'POST' && approveMatch) {
      const id = approveMatch[1]!;
      handleApprove(req, res, {
        approvalService: this.deps.approvalService,
        sessionToken: this.deps.sessionToken,
      }, id);
      return;
    }

    // POST /approvals/:id/deny
    const denyMatch = /^\/approvals\/([^/]+)\/deny$/.exec(pathname);
    if (method === 'POST' && denyMatch) {
      const id = denyMatch[1]!;
      handleDeny(req, res, {
        approvalService: this.deps.approvalService,
        sessionToken: this.deps.sessionToken,
      }, id);
      return;
    }

    // 404
    sendJson(res, 404, { success: false, error: 'Not found' });
  }

  // ── Private ───────────────────────────────────────────────────────────────

  /**
   * Build and send the initial system.status snapshot event to a newly
   * connected WebSocket client.
   */
  private sendSnapshot(ws: WebSocket): void {
    try {
      const snapshot = this.deps.getSnapshot();
      const event: CanvasEvent = {
        event_id: crypto.randomUUID(),
        event_type: 'system.status',
        task_id: null,
        tier: null,
        created_at: new Date().toISOString(),
        payload: snapshot as unknown as Record<string, unknown>,
      };
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify(event));
      }
    } catch (err) {
      this.deps.auditLog.write({
        timestamp: new Date().toISOString(),
        level: 'warn',
        service: 'CanvasServer',
        message: `Failed to send initial snapshot: ${(err as Error).message}`,
        action: 'canvas.ws.snapshot_error',
      });
    }
  }
}

// ── Canvas event factory helpers (used by ApexRuntime) ────────────────────────

/**
 * Build a CanvasEvent envelope with a fresh UUID and timestamp.
 * Caller provides event_type, task_id, tier, and payload.
 * Payload must never include credentials, tokens, or secrets.
 */
export function makeCanvasEvent(
  event_type: CanvasEvent['event_type'],
  payload: Record<string, unknown>,
  task_id: string | null = null,
  tier: CanvasEvent['tier'] = null,
): CanvasEvent {
  return {
    event_id: crypto.randomUUID(),
    event_type,
    task_id,
    tier,
    created_at: new Date().toISOString(),
    payload,
  };
}
